services:
  juno-satellite:
    image: junobuild/satellite:latest
    ports:
      - 5987:5987
    volumes:
      - juno_satellite:/juno/.juno
      - ./juno.dev.json:/juno/juno.dev.json
      - ./target/deploy:/juno/target/deploy/

volumes:
  juno_satellite:
