// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

// @ts-expect-error
export const idlFactory = ({ IDL }) => {
  return IDL.Service({ say: IDL.Func([], [], ["query"]) });
};
// @ts-expect-error
export const init = ({ IDL }) => {
  return [];
};
