// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

import type { _SERVICE as SatelliteActor } from "./satellite.did";
import { idlFactory } from "./satellite.factory.did.js";
import { getSatelliteExtendedActor } from "@junobuild/core";

export const say = async (): Promise<undefined> => {
  const { say } = await getSatelliteExtendedActor<SatelliteActor>({
    idlFactory,
  });

  return await say();
};
