// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck

import type {_SERVICE as SatelliteActor} from './satellite.did';
import type { Principal } from '@icp-sdk/core/principal';
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';

const buildVersion = async (): Promise<string> => {
	const {build_version} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await build_version();
}

export const functions = {
	buildVersion
};